import React, { useEffect, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { createClient } from '@supabase/supabase-js'
import { ArrowDownToLine, ArrowUpRight, BadgeCheck, BarChart3, Bell, Check, ChevronRight, CircleDollarSign, Clipboard, Coins, Crown, ExternalLink, Gift, History, Home, LayoutDashboard, Link2, ListChecks, LogOut, Menu, Search, Settings, ShieldCheck, Sparkles, TrendingUp, User, Users, WalletCards, X, Zap } from 'lucide-react'
import './styles.css'

const ADMIN_EMAILS = ['muhammaddanyal4949@gmail.com','muhammaddanyal4545@gmail.com']
const ADMIN_USERNAMES = ['danyal955','danyal955163','danyal1953']
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL
const SUPABASE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY
const supabase = SUPABASE_URL && SUPABASE_KEY ? createClient(SUPABASE_URL, SUPABASE_KEY) : null
if (!supabase) console.warn('[Cash Coin] Supabase is not configured. Demo mode is active; set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY for Lovable Cloud.')

const seedTasks = [
  { id:'t1', title:'Follow our Instagram', description:'Follow Cash Coin for earning tips and daily updates.', coins_reward:150, category:'Social', link:'https://instagram.com' },
  { id:'t2', title:'Join our Telegram community', description:'Join the official community and stay ahead of new offers.', coins_reward:250, category:'Community', link:'https://t.me' },
  { id:'t3', title:'Daily check-in', description:'Come back each day and collect your reward.', coins_reward:50, category:'Daily', link:'#' }
]
const seedUsers = [
  { id:'u1', email:'go421@gmail.com', username:'Go421', referral_code:'Go421', coins:1280, total_tasks:8, role:'user', referred_by:'Noot4349' },
  { id:'u2', email:'noot4349@gmail.com', username:'Noot4349', referral_code:'Noot4349', coins:3420, total_tasks:16, role:'user', referred_by:'—' },
  { id:'u3', email:'muhammaddanyal4949@gmail.com', username:'danyal955', referral_code:'danyal955', coins:5600, total_tasks:22, role:'admin', referred_by:'—' }
]
const money = n => `${Number(n || 0).toLocaleString()} PKR`
const isAdmin = (email, username) => ADMIN_EMAILS.includes((email||'').toLowerCase()) || ADMIN_USERNAMES.includes((username||'').toLowerCase())

function App(){
  const params = new URLSearchParams(location.search)
  const [session, setSession] = useState(null)
  const [profile, setProfile] = useState(null)
  const [page, setPage] = useState('home')
  const [authMode, setAuthMode] = useState(params.get('ref') ? 'register' : 'login')
  const [notice, setNotice] = useState(null)
  const [demo, setDemo] = useState(!supabase)
  const admin = isAdmin(profile?.email || session?.user?.email, profile?.username)

  useEffect(() => {
    if (!supabase) return
    supabase.auth.getSession().then(({data}) => { if(data.session) { setSession(data.session); loadProfile(data.session.user.id) } })
    const {data:{subscription}} = supabase.auth.onAuthStateChange((_event, next) => { setSession(next); if(next) loadProfile(next.user.id) })
    return () => subscription.unsubscribe()
  }, [])
  async function loadProfile(id){
    const {data,error} = await supabase.from('profiles').select('*').eq('id',id).single()
    if(error) console.error('[Cash Coin] Profile could not be initialized:', error)
    if(data) setProfile(data)
  }
  function show(message,type='success'){ setNotice({message,type}); setTimeout(()=>setNotice(null),4500) }
  function loginDemo(user){ setSession({user}); setProfile(user); setPage('home'); show('Welcome back to Cash Coin') }
  async function logout(){ if(supabase) await supabase.auth.signOut(); setSession(null); setProfile(null); setPage('home'); setAuthMode('login') }
  if(!session) return <><Auth mode={authMode} setMode={setAuthMode} refCode={params.get('ref')||''} onDemoLogin={loginDemo} show={show}/><Toast notice={notice}/></>
  return <div className="app-shell"><Header profile={profile} admin={admin} page={page} setPage={setPage} logout={logout}/><main className="main-content">{admin && page.startsWith('admin') ? <Admin page={page} setPage={setPage} show={show}/> : <UserApp page={page} setPage={setPage} profile={profile} show={show}/>}</main><BottomNav page={page} setPage={setPage} admin={admin}/><Toast notice={notice}/></div>
}

function Auth({mode,setMode,refCode,onDemoLogin,show}){
  const [form,setForm] = useState({email:'',username:'',password:'',confirm:'',ref:refCode})
  const [busy,setBusy] = useState(false)
  const update = e => setForm({...form,[e.target.name]:e.target.value})
  async function submit(e){
    e.preventDefault(); setBusy(true)
    if(mode==='register'){
      if(!/^[A-Za-z0-9]{4,15}$/.test(form.username)) { show('Username صرف letters اور numbers پر مشتمل ہو، 4 سے 15 حروف۔','error'); setBusy(false); return }
      if(!/(?=.*[A-Z])(?=.*\d).{6,}/.test(form.password)) { show('Password میں کم از کم ایک capital letter اور ایک number ہونا ضروری ہے۔','error'); setBusy(false); return }
      if(form.password!==form.confirm) { show('Passwords match نہیں کر رہے۔','error'); setBusy(false); return }
      if(supabase){ const {error}=await supabase.auth.signUp({email:form.email,password:form.password,options:{data:{username:form.username,referred_by:form.ref||null}}}); if(error){ console.error(error); show(error.message.includes('already')?'Ye Gmail pehle se registered hai, Login karein':error.message,'error') } else show('Account بن گیا! اپنی email verify کریں۔') }
      else { const user={id:'demo-'+Date.now(),email:form.email,username:form.username,referral_code:form.username,coins:0,total_tasks:0,role:isAdmin(form.email,form.username)?'admin':'user',referred_by:form.ref||'—'}; onDemoLogin(user) }
    } else {
      if(supabase){ const {data,error}=await supabase.auth.signInWithPassword({email:form.email,password:form.password}); if(error){show('Email یا password درست نہیں ہے۔','error')} else { show('Login successful'); } }
      else { const username=form.email.split('@')[0] || 'Go421'; onDemoLogin({id:'demo',email:form.email||'go421@gmail.com',username,referral_code:username,coins:1280,total_tasks:8,role:isAdmin(form.email,username)?'admin':'user',referred_by:'—'}) }
    }
    setBusy(false)
  }
  return <div className="auth-page"><div className="auth-visual"><div className="brand large"><span className="logo-mark">CC</span><span>Cash Coin</span></div><div className="visual-copy"><span className="eyebrow">YOUR EVERYDAY EARNING PARTNER</span><h1>Earn coins.<br/><em>Convert to cash.</em></h1><p>Complete simple tasks, invite friends, and turn your time into real rewards.</p><div className="visual-stats"><div><strong>10K+</strong><span>Earners</span></div><div><strong>₨2.4M</strong><span>Paid out</span></div><div><strong>4.9/5</strong><span>Rating</span></div></div></div></div><div className="auth-card-wrap"><div className="mobile-brand brand"><span className="logo-mark">CC</span><span>Cash Coin</span></div><div className="auth-card"><div className="auth-heading"><span className="mini-icon"><Sparkles size={17}/></span><span>{mode==='login'?'Welcome back':'Start earning today'}</span><h2>{mode==='login'?'Log in to your account':'Create your account'}</h2><p>{mode==='login'?'Your coins are waiting for you.':'Join thousands of people earning with Cash Coin.'}</p></div><form onSubmit={submit}>{mode==='register'&&<><label>Username<input name="username" value={form.username} onChange={update} placeholder="e.g. Go421" required/><small>4–15 characters, letters and numbers only</small></label></>}<label>Email address<input name="email" type="email" value={form.email} onChange={update} placeholder="you@gmail.com" required/></label><label>Password<input name="password" type="password" value={form.password} onChange={update} placeholder="••••••••" required/></label>{mode==='register'&&<><label>Confirm password<input name="confirm" type="password" value={form.confirm} onChange={update} placeholder="••••••••" required/></label><label>Invite code <span className="optional">(optional)</span><input name="ref" value={form.ref} onChange={update} placeholder="e.g. Noot4349"/><small>{form.ref ? `Invited by ${form.ref}` : 'Have a friend? Add their code to earn bonus coins.'}</small></label></>}<button className="primary-btn full" disabled={busy}>{busy?'Please wait…':mode==='login'?'Log in':'Create account'}<ChevronRight size={18}/></button></form><div className="auth-switch">{mode==='login'?<>Don't have an account? <button onClick={()=>setMode('register')}>Create one</button></>:<>Already have an account? <button onClick={()=>setMode('login')}>Log in</button></>}</div><div className="secure-note"><ShieldCheck size={15}/> Your data is secure and encrypted</div></div></div></div>
}

function Header({profile,admin,page,setPage,logout}){ return <header className="topbar"><div className="brand"><span className="logo-mark">CC</span><span>Cash Coin</span></div><div className="top-actions"><button className="icon-btn"><Bell size={19}/><i/></button>{admin&&<button className="admin-pill" onClick={()=>setPage('admin-dashboard')}><Crown size={15}/> Admin Panel</button>}<div className="avatar">{(profile?.username||'U').slice(0,1).toUpperCase()}</div><button className="icon-btn logout" onClick={logout}><LogOut size={18}/></button></div></header> }
function BottomNav({page,setPage,admin}){ const items=[['home','Home',Home],['tasks','Tasks',ListChecks],['offers','Offers',Gift],['wallet','Wallet',WalletCards],['profile','Profile',User]]; return <nav className="bottom-nav">{items.map(([id,label,Icon])=><button key={id} className={page===id?'active':''} onClick={()=>setPage(id)}><Icon size={20}/><span>{label}</span></button>)}</nav> }
function UserApp({page,setPage,profile,show}){ if(page==='tasks') return <Tasks show={show} setPage={setPage}/>; if(page==='wallet') return <Wallet profile={profile} show={show}/>; if(page==='offers') return <Offers/>; if(page==='profile') return <Profile profile={profile} show={show}/>; return <Dashboard profile={profile} setPage={setPage} show={show}/> }
function Dashboard({profile,setPage,show}){ const code=profile?.referral_code||profile?.username||'Go421'; const link=`https://cash-coin.vercel.app/register?ref=${code}`; return <div className="page"><div className="welcome-row"><div><span className="eyebrow purple">OVERVIEW</span><h1>Good evening, {profile?.username||'earner'} <span>✦</span></h1><p>Keep going — your next reward is just a task away.</p></div><button className="circle-action"><Bell size={20}/></button></div><div className="balance-grid"><div className="balance-card"><div className="balance-top"><span>Total balance</span><span className="live-dot">● Live</span></div><strong>{money((profile?.coins||0)/100)}</strong><div className="balance-bottom"><span><Coins size={16}/> {(profile?.coins||0).toLocaleString()} coins</span><span>100 coins = 1 PKR</span></div></div><div className="stat-card"><span>Tasks completed</span><strong>{profile?.total_tasks||0}</strong><span className="stat-trend"><TrendingUp size={15}/> Keep it up</span></div><div className="stat-card"><span>Referral earnings</span><strong>+250</strong><span className="stat-trend"><Users size={15}/> 5 friends joined</span></div></div><div className="section-heading"><div><h2>Invite & earn</h2><p>Get 50 coins for every friend who joins.</p></div><Gift className="section-icon" size={22}/></div><div className="referral-card"><div className="referral-main"><div className="referral-icon"><Link2 size={22}/></div><div><span>Your referral link</span><strong>{link}</strong></div></div><div className="referral-actions"><button className="copy-btn" onClick={()=>{navigator.clipboard?.writeText(link);show('Referral link copied!')}}><Clipboard size={16}/> Copy link</button><button className="share-btn" onClick={()=>navigator.share?.({title:'Cash Coin',url:link})}><ArrowUpRight size={16}/></button></div></div><div className="section-heading space-top"><div><h2>Quick actions</h2><p>Simple ways to grow your balance.</p></div></div><div className="quick-grid"><button onClick={()=>setPage('tasks')}><span className="quick-icon purple-bg"><Zap/></span><b>Complete tasks</b><small>Earn up to 500 coins</small><ChevronRight/></button><button onClick={()=>setPage('wallet')}><span className="quick-icon green-bg"><ArrowDownToLine/></span><b>Withdraw cash</b><small>Fast & secure payouts</small><ChevronRight/></button></div></div> }
function Tasks({show,setPage}){ const [completed,setCompleted]=useState([]); return <div className="page"><PageTitle eyebrow="EARN COINS" title="Available tasks" subtitle="Complete tasks and turn your time into rewards." action={<span className="coins-chip"><Coins size={15}/> 0 coins</span>}/><div className="filter-row"><button className="filter active">All tasks</button><button className="filter">Social</button><button className="filter">Daily</button><button className="filter">Community</button></div><div className="task-list">{seedTasks.map((t,i)=><div className="task-card" key={t.id}><div className={`task-icon task-${i}`}><ExternalLink size={20}/></div><div className="task-copy"><div className="task-meta"><span>{t.category}</span><small>5 min</small></div><h3>{t.title}</h3><p>{t.description}</p><button onClick={()=>{setCompleted([...completed,t.id]);show('Task opened — submit your proof when done.')}}>{completed.includes(t.id)?'Proof submitted':'Start task'} <ArrowUpRight size={15}/></button></div><div className="reward">+{t.coins_reward}<small>coins</small></div></div>)}</div><div className="info-banner"><Sparkles size={20}/><div><b>New tasks every day</b><p>Check back regularly to never miss an earning opportunity.</p></div></div></div> }
function Wallet({profile,show}){ const [withdraw,setWithdraw]=useState(false); return <div className="page"><PageTitle eyebrow="YOUR WALLET" title="Wallet" subtitle="Manage your coins and cash withdrawals."/><div className="wallet-hero"><span>Available balance</span><strong>{(profile?.coins||0).toLocaleString()} <small>coins</small></strong><b>≈ {money((profile?.coins||0)/100)}</b><button className="primary-btn" onClick={()=>setWithdraw(true)}><ArrowDownToLine size={17}/> Withdraw</button></div><div className="wallet-stats"><div><span>Coin rate</span><b>100 = 1 PKR</b></div><div><span>Minimum withdrawal</span><b>500 coins</b></div></div><div className="section-heading space-top"><div><h2>Recent activity</h2><p>Your latest wallet movements.</p></div><History size={21} className="muted"/></div><div className="activity-list"><Activity icon={<Gift/>} title="Welcome bonus" date="Today, 10:24 AM" amount="+250"/><Activity icon={<BadgeCheck/>} title="Task reward" date="Yesterday" amount="+150"/><Activity icon={<ArrowDownToLine/>} title="Withdrawal" date="Sep 22, 2026" amount="−500" negative/></div>{withdraw&&<Modal title="Withdraw cash" close={()=>setWithdraw(false)}><p className="modal-help">Withdrawals are processed within 24 hours. Minimum 500 coins.</p><label>Amount in coins<input type="number" placeholder="500"/></label><label>Payment method<select><option>JazzCash</option><option>Easypaisa</option><option>Bank</option></select></label><label>Account number<input placeholder="03XX XXXXXXX"/></label><label>Account title<input placeholder="Your full name"/></label><button className="primary-btn full" onClick={()=>{setWithdraw(false);show('Withdrawal request submitted for review.')}}>Submit withdrawal</button></Modal>}</div> }
function Activity({icon,title,date,amount,negative}){return <div className="activity"><span className="activity-icon">{icon}</span><div><b>{title}</b><small>{date}</small></div><strong className={negative?'negative':''}>{amount} coins</strong></div>}
function Offers(){return <div className="page"><PageTitle eyebrow="SPECIAL OFFERS" title="Offers" subtitle="Limited-time bonuses made for you."/><div className="offer-banner"><div><span className="eyebrow">CASH COIN EXCLUSIVE</span><h2>Double your first<br/>withdrawal reward.</h2><p>Invite 3 friends this week and unlock a 2× bonus.</p><button className="light-btn">Learn more <ArrowUpRight size={15}/></button></div><div className="offer-art"><Coins size={100}/><Sparkles size={30}/></div></div><div className="offer-grid"><div className="offer-card"><span className="offer-label green">POPULAR</span><h3>Refer & earn</h3><p>Invite friends and get 50 coins for every successful signup.</p><button>Invite now <ChevronRight size={15}/></button></div><div className="offer-card"><span className="offer-label purple">DAILY</span><h3>Daily streak</h3><p>Check in for 7 days straight and get a 500 coin bonus.</p><button>Start streak <ChevronRight size={15}/></button></div></div></div>}
function Profile({profile,show}){ const code=profile?.referral_code||profile?.username; return <div className="page"><PageTitle eyebrow="ACCOUNT" title="Profile" subtitle="Your Cash Coin account details."/><div className="profile-card"><div className="profile-avatar">{(profile?.username||'U').slice(0,1).toUpperCase()}</div><h2>{profile?.username||'Demo User'}</h2><p>{profile?.email||'go421@gmail.com'}</p><span className="verified"><BadgeCheck size={14}/> Verified account</span></div><div className="details-card"><Detail label="Username" value={profile?.username||'Go421'}/><Detail label="Email address" value={profile?.email||'go421@gmail.com'}/><Detail label="Referral code" value={code||'Go421'}/><Detail label="Member since" value="September 2026"/></div><button className="outline-btn full" onClick={()=>show('Profile settings are ready for your next update.') }><Settings size={17}/> Account settings</button></div>}
function Detail({label,value}){return <div className="detail"><span>{label}</span><b>{value}</b></div>}
function PageTitle({eyebrow,title,subtitle,action}){return <div className="page-title"><div><span className="eyebrow purple">{eyebrow}</span><h1>{title}</h1><p>{subtitle}</p></div>{action}</div>}
function Admin({page,setPage,show}){ const section=page.replace('admin-','')||'dashboard'; const items=[['dashboard','Dashboard',LayoutDashboard],['users','Users',Users],['tasks','Tasks',ListChecks],['withdrawals','Withdrawals',ArrowDownToLine],['deposits','Deposits',ArrowUpRight],['accounts','Payment Accounts',WalletCards],['settings','Settings',Settings]]; return <div className="admin-layout"><aside className="admin-sidebar"><div className="admin-title"><Crown size={19}/> Admin workspace</div><p>Manage Cash Coin operations</p><nav>{items.map(([id,label,Icon])=><button className={section===id?'active':''} onClick={()=>setPage('admin-'+id)} key={id}><Icon size={18}/>{label}<ChevronRight size={15}/></button>)}</nav><div className="admin-side-foot"><ShieldCheck size={17}/><span>Admin access<br/><b>Protected workspace</b></span></div></aside><div className="admin-content"><div className="admin-mobile-nav"><Menu size={19}/><b>Admin Panel</b></div>{section==='dashboard'?<AdminDashboard setPage={setPage}/>:section==='users'?<AdminUsers/>:section==='tasks'?<AdminTasks show={show}/>:<AdminPlaceholder title={items.find(x=>x[0]===section)?.[1]||'Settings'} />}</div></div> }
function AdminDashboard({setPage}){return <div className="page admin-page"><PageTitle eyebrow="ADMIN PANEL" title="Good evening, Danyal" subtitle="Here’s what’s happening across Cash Coin today." action={<span className="date-pill">September 26, 2026</span>}/><div className="admin-metrics"><Metric label="Total users" value="4" change="+12.5%" icon={<Users/>}/><Metric label="Total coins in circulation" value="10,300" change="+8.2%" icon={<Coins/>}/><Metric label="Pending withdrawals" value="2" change="Needs review" icon={<ArrowDownToLine/>}/><Metric label="Pending task proofs" value="5" change="Needs review" icon={<ListChecks/>}/></div><div className="admin-columns"><div className="panel"><div className="panel-heading"><div><h2>Recent activity</h2><p>Latest actions from your community.</p></div><button onClick={()=>setPage('admin-users')}>View all</button></div><Activity icon={<Users/>} title="New user registered" date="Go421 joined via Noot4349" amount="+1"/><Activity icon={<BadgeCheck/>} title="Task proof approved" date="Instagram task · Go421" amount="+150"/><Activity icon={<ArrowDownToLine/>} title="Withdrawal requested" date="JazzCash · 500 coins" amount="Review"/></div><div className="panel overview-panel"><div className="panel-heading"><div><h2>Quick overview</h2><p>Performance snapshot.</p></div></div><div className="donut"><strong>76%</strong><span>task<br/>completion</span></div><div className="legend"><span><i className="dot purple-dot"/> Active users <b>76%</b></span><span><i className="dot gray-dot"/> Inactive <b>24%</b></span></div></div></div></div>}
function Metric({label,value,change,icon}){return <div className="metric"><span className="metric-icon">{icon}</span><span>{label}</span><strong>{value}</strong><small>{change}</small></div>}
function AdminUsers(){const [q,setQ]=useState('');const users=seedUsers.filter(u=>(u.email+u.username).toLowerCase().includes(q.toLowerCase()));return <div className="page admin-page"><PageTitle eyebrow="USER MANAGEMENT" title="Users" subtitle="View and manage every Cash Coin member." action={<button className="primary-btn"><Users size={16}/> Invite user</button>}/><div className="table-toolbar"><div className="search-box"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search by email or username"/></div><button className="filter"><span>All users</span><ChevronRight size={15}/></button></div><div className="data-table"><div className="table-head"><span>User</span><span>Referral code</span><span>Balance</span><span>Role</span><span>Status</span><span/></div>{users.map(u=><div className="table-row" key={u.id}><div className="user-cell"><span className="table-avatar">{u.username.slice(0,1)}</span><span><b>{u.username}</b><small>{u.email}</small></span></div><span>{u.referral_code}</span><span><b>{u.coins.toLocaleString()}</b> coins</span><span><em className={u.role==='admin'?'role-admin':'role-user'}>{u.role}</em></span><span><i className="status-dot"/> Active</span><button className="more-btn">•••</button></div>)}</div></div>}
function AdminTasks({show}){return <div className="page admin-page"><PageTitle eyebrow="TASK MANAGEMENT" title="Tasks" subtitle="Create offers and review submitted proofs." action={<button className="primary-btn" onClick={()=>show('Create task form is ready to connect to your Supabase table.')}><Zap size={16}/> Create task</button>}/><div className="admin-tabs"><button className="active">All tasks <b>3</b></button><button>Pending proofs <b className="red">5</b></button><button>Inactive <b>0</b></button></div><div className="admin-task-list">{seedTasks.map(t=><div className="admin-task-row" key={t.id}><span className="task-icon task-0"><ListChecks size={18}/></span><div><b>{t.title}</b><small>{t.category} · {t.link}</small></div><span className="reward-pill">+{t.coins_reward} coins</span><span className="active-pill"><i/> Active</span><button className="more-btn">•••</button></div>)}</div></div>}
function AdminPlaceholder({title}){return <div className="page admin-page"><PageTitle eyebrow="ADMIN PANEL" title={title} subtitle="This section is connected to the Cash Coin management workspace."/><div className="empty-state"><span><Settings size={25}/></span><h2>{title} overview</h2><p>Records will appear here once your Supabase Cloud project is connected and seeded with the included schema.</p></div></div>}
function Modal({title,close,children}){return <div className="modal-backdrop" onClick={close}><div className="modal" onClick={e=>e.stopPropagation()}><div className="modal-head"><h2>{title}</h2><button onClick={close}><X size={18}/></button></div>{children}</div></div>}
function Toast({notice}){return notice?<div className={`toast ${notice.type==='error'?'error':''}`}><Check size={16}/>{notice.message}</div>:null}

createRoot(document.getElementById('root')).render(<App />)
